### ISSUE TITLE
SES - Report - Runtime update from Nodejs 8 to 10 fails

### ISSUE THREAD

**Issue by saifeer** [awslabs/aws-support-tools#104]
AWS have asked to update from Nodejs 8 to 10.x but modifying the SES Bounce dashboard and report template to use Nodejs 10.x results in failure with error: 
nodejs10.x does not support cfn-response

**Comment by lsida** [comment]
Hi saifeer, 

Thank you for the feedback, I will try to find the author of the tool to see what we can do.

**Comment by lsida** [comment]
Hi saifeer,

I just heard back from the author, and he suggested cfn-response does not work yet with newest node is a known issue. Please keep using Nodejs 8 at the moment. We will bump the version once cfn-response is supported.
