### ISSUE TITLE
**CloudWatch Logs** [ERROR] Runtime.ImportModuleError: Unable to import module 'lambda_function': No module named 'salesforce'

### ISSUE THREAD

**Issue by bhaskararora** [awslabs/aws-support-tools#107]
https://github.com/AmazonConnectSalesforceIntegration/AmazonConnectSalesforceLambda/tree/20d07b9098db3c477dbc6c8821cc1913264da610/sam-app/lambda_functions

Getting Error : while analyzing above code on : **CloudWatch Logs** 
[ERROR] Runtime.ImportModuleError: Unable to import module 'lambda_function': No module named 'salesforce'

**Comment by lsida** [comment]
Hi @bhaskararora , please submit an issue under repo AmazonConnectSalesforceLambda.
