### ISSUE TITLE
SES Reports - filenames are not valid in windows

### ISSUE THREAD

**Issue by RobinSmithCA** [awslabs/aws-support-tools#12]
Colon is not a valid character for a filename in Windows.  So while these files are saved to S3 and working great there, I wouldn't be able to download the to a windows 10 system without some form of name conversion.  It would be better if they were named something more like this:

YYYYMMDDThhmmss.html (i.e. 20170308T135352.html)

Thanks!

**Comment by rsavordelli** [comment]
Hi,

The pull request for this fix was sent, soon you can update the lambda function with the new code, or change manually update your lambda code replacing the date variable for the following;
https://github.com/awslabs/aws-support-tools/pull/13/commits/c1bfe4b7ab0fa7d8dc87365a2d2090b3a71448c7

The new format is:
Aug-01-2017-08-15-44.html

If you want to use as a timestamp format, you can replace the variable date for something like the following:
var date = (new Date()).toISOString().replace(/T/, '').replace(/\..+/, '').replace(/:/g,'').replace(/-/g, '')

**Comment by ssamed** [comment]
Fixed merged.
