### ISSUE TITLE
SESMailer:- incorrect header check Error

### ISSUE THREAD

**Issue by Aamir010** [awslabs/aws-support-tools#16]
Can anyone please help me to resolve this error.

Error -3 while decompressing data: incorrect header check Aborting...
Error -3 while decompressing data: incorrect header check: error
Traceback (most recent call last):
File "/var/task/lambda_function.py", line 136, in lambda_handler
raise e
error: Error -3 while decompressing data: incorrect header check

**Comment by ssamed** [comment]
Are you uploading files compressed using gzip compression? The error indicates this:

error: Error -3 while decompressing data: incorrect header check.

**Comment by joshua-at-aws** [comment]
I'm going to go ahead and close this out as it's been a few months, feel free to send us a PR if you wanted to add additional checks!
