### ISSUE TITLE
python-jose not part of the lambda environment?

### ISSUE THREAD

**Issue by gg0512** [awslabs/aws-support-tools#34]
Hello, I am trying to use the code here to verify if a token is valid
[/Cognito/decode-verify-jwt/decode-verify-jwt.py](https://github.com/awslabs/aws-support-tools/blob/master/Cognito/decode-verify-jwt/decode-verify-jwt.py)
But I am facing an issue. My Lambda doesn't recognize jose.
`Unable to import module 'lambda_function': No module named 'jose'`

**Comment by emanuelem** [comment]
Hello,

Thank you for pointing that out. It actually seems that python-jose is not part of the Lambda environment anymore.
At this point, the only way is to [add it to the Lambda deployment package](https://docs.aws.amazon.com/lambda/latest/dg/lambda-python-how-to-create-deployment-package.html).

**Comment by gg0512** [comment]
Thanks for answering me.
However, when adding a deployment package, I run into another error: 
`module initialization error: Cannot load native module 'Crypto.Hash._SHA256': Trying '_SHA256.so': /var/task/Crypto/Util/../Hash/_SHA256.so: invalid ELF header, Trying '_SHA256module.so': /var/task/Crypto/Util/../Hash/_SHA256module.so: cannot open shared object file: No such file or directory`
I am using Python 2.7

**Comment by emanuelem** [comment]
The error "invalid ELF header" means that the binaries you added to the deployment package were compiled for another architecture. For example, it is common to see this error if the package was installed with "pip" under Mac.

An easy solution is to spin up an EC2 instance, then install the modules and create the deployment package there. This will include the same binaries used by the Lambda environment.

**Comment by gg0512** [comment]
**Solution:**
I started an EC2 instance as you suggested, but with the same environment as Lambdas (just to be sure).
[Lambda AMI](https://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html)

Execute this on EC2. This creates the deployment package and sends it to a S3 bucket :
```
$sudo yum group install "Development Tools"
$mkdir lambda
$sudo pip install --upgrade pip
$hash -r
$pip install python-jose -t lambda/
$pip install cryptography -t lambda/
$zip -r Archive.zip lambda
$aws configure
$aws s3api put-object --bucket <<Bucket_Name>> --key Archive.zip --body Archive.zip 
```
