### ISSUE TITLE
invalid syntax (jose.py, line 546)

### ISSUE THREAD

**Issue by vishaldesai** [awslabs/aws-support-tools#36]
I want to use same functionality from aws lambda. Code works on local machine but from cloud9 or lambda I get following error:
Syntax error in module 'customauthorizer3/lambda_function': invalid syntax (jose.py, line 546)

**Comment by emanuelem** [comment]
The [python-jose](https://github.com/mpdavis/python-jose) module doesn't seem to contain the file "jose.py". Can you confirm what modules you're using and how you included them in the Lambda deployment package?

**Comment by vishaldesai** [comment]
Sorry I was using plain jose. It works with python-jose.

Thanks
