### ISSUE TITLE
SESMailer: connection pool is full

### ISSUE THREAD

**Issue by paulbrab** [awslabs/aws-support-tools#37]
Hi,

I followed the docs @ https://aws.amazon.com/premiumsupport/knowledge-center/mass-email-ses-lambda/

When I run this suing a csv file with 22 rows, I had the following log warning 4 times:
"Connection pool is full, discarding connection: email.us-west-2.amazonaws.com"

Does connection discarded = no email sent?

Also, when trying with 10,000 rows, I receive the above multiple times and eventually I run into the following:
```
can't start new thread: error
Traceback (most recent call last):
File "/var/task/lambda_function.py", line 137, in lambda_handler
raise e
error: can't start new thread
```
And sending is aborted

**Comment by paulbrab** [comment]
Thanks for the quick reply.

When you say "larger Lambda size", I'm guessing you are referring to memory?

So I tried increasing the memory to max (3008MB)
I uploaded a gz file with 10,000 rows. The first row recipient is my own email. The next 9,998 emails are the success simulator address. The final row is, again, my address. The subject of the first row (my email) is "test email start" and the last row (my email) is "test email end".

The lambda function kicked off and I ended up getting all the same errors as above and also received the first email 3 times so far. I haven't received the last email at all.

**Comment by paulbrab** [comment]
Bit disappointing for AWS to close this without any further comment. I thought you were trying to get developers to use your services? We send almost half a million emails in a single send. Was hoping to make use of lambda to help with scaling and sending speed.

**Comment by ssamed** [comment]
This tool uses SES and Lambda service both of which have defined limits. Looking into your cloudwatch logs will help you determine the cause of the failure and in case you require SES or Lambda rate limits increased. Also, these tools help customers come up with ideas and help them innovate but they are by no means meant to be the final iteration  and ready for production use. You are welcome to base your solution on this and improve its performance such as self throttling based on SES limits or better error logging.
