### ISSUE TITLE
Delivery support

### ISSUE THREAD

**Issue by gcormier** [awslabs/aws-support-tools#40]
Feature request to allow reporting as well on delivery success messages.

**Comment by gcormier** [comment]
Yup, exactly. I've done some hacking to get it going, but I don't think it's in the best format for sharing.

I had to shift a few things around, as some fields are not present in delivery, that were present in the other 3. For what it's worth, here's the code. I'm not sure if this would work correctly for an email that is sent to multiple recipients? Not sure if AWS split those up into seperate messages.

`if (data.Messages) {
                    var message = data.Messages[0];
                    body = JSON.parse(message.Body);
                    msg = JSON.parse(body.Message);

                    //console.log("Message*****");
                    //console.log(msg);

                    
                    var type = msg.notificationType;


                    if (type == "Bounce") {
                        var time;
                        var destination = msg.mail.destination[0];
                        var id = msg.mail.messageId;
                        var otr = "<tr>";
                        var ftr = "</tr>";
                        var oline = "<td>";
                        var cline = "</td>";
                        var btype = null;
                        var bsubtype = null;
                        var diagcode = null;

                        btype = msg.bounce.bounceType; // Permanent || Transient
                        bsubtype = msg.bounce.bounceSubType; // General || Supressed
                        time = msg.mail.timestamp;

                        if (btype == "Permanent" && bsubtype == "Suppressed") {
                            diagcode = "Suppressed by SES";
                            text = otr + oline + type + cline + oline + btype + cline + oline + bsubtype + cline + oline + destination + cline + oline + diagcode + cline + oline + time + cline + oline + id + cline + ftr;
                            msgSuppres.push(text);

                        }
                        else if (btype == "Permanent" && bsubtype == "General") {
                            diagcode = msg.bounce.bouncedRecipients[0].diagnosticCode;
                            text = otr + oline + type + cline + oline + btype + cline + oline + bsubtype + cline + oline + destination + cline + oline + diagcode + cline + oline + time + cline + oline + id + cline + ftr;
                            msgBouncePerm.push(text);

                        }
                        else if (btype == "Permanent" && bsubtype == "NoEmail") {
                            diagcode = msg.bounce.bouncedRecipients[0].diagnosticCode;
                            text = otr + oline + type + cline + oline + btype + cline + oline + bsubtype + cline + oline + destination + cline + oline + diagcode + cline + oline + time + cline + oline + id + cline + ftr;
                            msgBouncePerm.push(text);

                        }
                        else if (btype == "Undetermined") {
                            diagcode = msg.bounce.bouncedRecipients[0].diagnosticCode;
                            text = otr + oline + type + cline + oline + btype + cline + oline + bsubtype + cline + oline + destination + cline + oline + diagcode + cline + oline + time + cline + oline + id + cline + ftr;
                            msgBouncePerm.push(text);

                        }
                        else if (btype == "Transient") {
                            diagcode = "soft-Bounce";
                            text = otr + oline + type + cline + oline + btype + cline + oline + bsubtype + cline + oline + destination + cline + oline + diagcode + cline + oline + time + cline + oline + id + cline + ftr;
                            msgBounceTrans.push(text);

                        }
                        else {
                            console.log("it's an unknown bounce");
                            diagcode = "unknown";
                            text = otr + oline + type + cline + oline + btype + cline + oline + bsubtype + cline + oline + destination + cline + oline + diagcode + cline + oline + time + cline + oline + id + cline + ftr;
                            msgBouncePerm.push(text);
                        }

                    }
                    else if (type == "Delivery") {
                        var time;
                        var destination = msg.mail.destination[0];
                        var id = msg.mail.messageId;
                        var otr = "<tr>";
                        var ftr = "</tr>";
                        var oline = "<td>";
                        var cline = "</td>";
                        var btype = null;
                        var bsubtype = null;
                        var diagcode = null;
                        time = msg.delivery.timestamp;
                        btype = "Delivery";
                        bsubtype = "General";
                        diagcode = msg.mail.commonHeaders.subject;

                        text = otr + oline + type + cline + oline + btype + cline + oline + bsubtype + cline + oline + destination + cline + oline + diagcode + cline + oline + time + cline + oline + id + cline + ftr;

                        msgDelivery.push(text);

                    }
                    else if (type == "Complaint") {
                        var time;
                        var destination = msg.mail.destination[0];
                        var id = msg.mail.messageId;
                        var otr = "<tr>";
                        var ftr = "</tr>";
                        var oline = "<td>";
                        var cline = "</td>";
                        var btype = null;
                        var bsubtype = null;
                        var diagcode = null;
                        time = msg.mail.timestamp;
                        btype = "null";
                        bsubtype = "null";
                        diagcode = "null";
                        text = otr + oline + type + cline + oline + btype + cline + oline + bsubtype + cline + oline + destination + cline + oline + diagcode + cline + oline + time + cline + oline + id + cline + ftr;

                        msgComplaint.push(text);

                    }

                    else {
                        console.log("not identified");
                    }

                    messages.push(i);

                    deleteMessage(message);
                    
                    //console.log("Array size = " + messages.length + " with queue size = " + queueSize);

                    if (messages.length == queueSize) {

                        var bp = msgBouncePerm.join('');
                        var sp = msgSuppres.join('');
                        var bt = msgBounceTrans.join('');
                        var cp = msgComplaint.join('');
                        var delivery = msgDelivery.join('');

                        var begin = fs.readFileSync('template/begin.html', 'utf8');
                        var middle = bp + sp + bt + cp + delivery;
                        var end = fs.readFileSync('template/end.html', 'utf8');
                        content = begin + middle + end;

                        s3upload();

                    }
                }
                else {
                    console.log("data without messages.");
                }`

**Comment by rsavordelli** [comment]
I'd not recommend implementing this dashboard for delivery notifications.  Mainly if your sending volume is high. The tool workflow is the following:
SES > SQS
Then, CloudWatch once a day trigger a lambda funcion that will pull all the messages collected from the SQS in that day, process the messages and create a static page in your s3 bucket. 

The issue with the delivery notification is that it generates a lot of notifications (way more than bounces and complaints) and I'm afraid the 5 minutes lambda time out will not be enough to process a lot of messages.

This code was tested with 50.000 messages in the queue. So if you have more than 50.000 messages (combining delivery, bounces, and complaints) in the queue, 5 minutes will not be enough to process.

**Comment by joshua-at-aws** [comment]
Hi,

Lambda now supports up to 15 minutes, but you have a good point about a large number of messages in the queue. 

I'll close this for now but please feel free to open a pull request if needed.
