### ISSUE TITLE
What library to use for Python 3.5, the 2.7 library python-jose does not work

### ISSUE THREAD

**Issue by EricAtPrendo** [awslabs/aws-support-tools#45]
I also tried to use: pyJWT which should work in 3.5, but could not get it to work with Cognito data.

**Comment by emanuelem** [comment]
Hi,

python-jose should be compatible with Python 3.x, but I also encountered some issues in how the string/bytes conversion is handled. [This](https://github.com/mpdavis/python-jose/issues/74) helped me to overcome the first error, but it generates other errors later in the code.
I'll need some time to test other libraries until I find one that works. In the meanwhile I suggest to stick with Python 2.7 or Node.js.

**Comment by jonathan-kosgei** [comment]
@emanuelem I ran into this too, see https://github.com/mpdavis/python-jose/issues/90

The changes needed to make it work with Python 3 are;

```
    decoded_signature = base64url_decode(encoded_signature.encode('utf-8'))
    # verify the signature
    if not public_key.verify(message.encode('utf-8'), str(decoded_signature)):
        print('Signature verification failed')
        return False
```

**Comment by emanuelem** [comment]
@jonathan-kosgei good finding! I did use encoded_signature.encode('utf-8'), but I didn't think about using encode() in public_key.verify() as well.
However I get an error when I use str(decoded_signature), in my cases it works with just decoded_signature.
