### ISSUE TITLE
error with python 2.7 

### ISSUE THREAD

**Issue by shyamkumarchauhan** [awslabs/aws-support-tools#54]
{
  "stackTrace": [
    [
      "/var/task/lambda_function.py",
      127,
      "lambda_handler",
      "raise e"
    ]
  ],
  "errorType": "KeyError",
  "errorMessage": "'Records'"
}

**Comment by joshua-at-aws** [comment]
Looks like you opened https://github.com/awslabs/aws-support-tools/issues/55 as well.
