### ISSUE TITLE
Error while using this script with ses and lambda

### ISSUE THREAD

**Issue by shyamkumarchauhan** [awslabs/aws-support-tools#55]
No older events found at the moment. Retry.

10:09:52
START RequestId: fb6a0552-bb2a-11e8-b033-c3ce03582e7f Version: $LATEST 
START RequestId: fb6a0552-bb2a-11e8-b033-c3ce03582e7f Version: $LATEST

10:09:52
'NoneType' object has no attribute 'strip' Aborting... 
'NoneType' object has no attribute 'strip' Aborting...

10:09:52
'NoneType' object has no attribute 'strip': AttributeError Traceback (most recent call last): File "/var/task/lambda_function.py", line 127, in lambda_handler raise e AttributeError: 'NoneType' object has no attribute 'strip' 
'NoneType' object has no attribute 'strip': AttributeError
Traceback (most recent call last):
File "/var/task/lambda_function.py", line 127, in lambda_handler
raise e
AttributeError: 'NoneType' object has no attribute 'strip'


10:09:52
END RequestId: fb6a0552-bb2a-11e8-b033-c3ce03582e7f 
END RequestId: fb6a0552-bb2a-11e8-b033-c3ce03582e7f

10:09:52
REPORT RequestId: fb6a0552-bb2a-11e8-b033-c3ce03582e7f Duration: 275.54 ms Billed Duration: 300 ms Memory Size: 128 MB Max Memory Used: 49 MB 
REPORT RequestId: fb6a0552-bb2a-11e8-b033-c3ce03582e7f Duration: 275.54 ms Billed Duration: 300 ms Memory Size: 128 MB Max Memory Used: 49 MB

**Comment by joshua-at-aws** [comment]
Hello,

Which tool from https://github.com/awslabs/aws-support-tools/tree/master/SES are you using?
