### ISSUE TITLE
SES - Report - The runtime parameter of nodejs4.3 is no longer supported

### ISSUE THREAD

**Issue by laggeduout** [awslabs/aws-support-tools#67]
When deploying the version of nodejs4.3 is not longer supported

`The runtime parameter of nodejs4.3 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs8.10) while creating or updating functions. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: a16f0820-02c2-11e9-89ad-e79c9bbbaebc)`

**Comment by rsavordelli** [comment]
The code is fully compatible with nodeJS6.10.

Please change the ses-reports.yaml to use nodejs6.10 instead of 4.3. I'm also changing the source code to use the new one.

Lines to be changed:
131
312

**Comment by lpierillas** [comment]
Tool has been updated to node8.10 #85
