### ISSUE TITLE
ses_mailer.py can cause thread issues in high volume sends

### ISSUE THREAD

**Issue by oscargws** [awslabs/aws-support-tools#68]
When attempting to send over 1000 emails using the SESMailer, you'll run into this error. This has been noted in issue #37 

```
can't start new thread: error
Traceback (most recent call last):
File "/var/task/lambda_function.py", line 132, in lambda_handler
raise e
error: can't start new thread
```

This is due to the ThreadPoolExecutor not being used with a `with` statement as per the python docs suggest ( [python docs for ThreadPoolExecutor](https://docs.python.org/3/library/concurrent.futures.html). )

**Comment by emanuelem** [comment]
Thank you for pointing it out. I've merged your edits.
