### ISSUE TITLE
ENA driver version check should be consistent with recommendation from docs

### ISSUE THREAD

**Issue by danvaida** [awslabs/aws-support-tools#72]
The script currently produces an output like:
```bash
"OK     ENA Module with version 1.1.2 is installed and available on your instance"
```
However, on the docs page, we see the mention that the minimum recommended version for the driver is actually `1.5.0g`: https://github.com/awsdocs/amazon-ec2-user-guide/blob/master/doc_source/enhanced-networking-ena.md#testing-whether-enhanced-networking-is-enabled
I think we should update the script to make it consistent with the docs. Let me know if a PR would be desired.

**Comment by orecht** [comment]
Which script produces this output?

**Comment by lsida** [comment]
Close the issue for now. Hi @danvaida , please suggest which script in this repo gives that output, and reopen the issue.
