### ISSUE TITLE
Cognito decode-verify-jwt.js works but does not return email in claims

### ISSUE THREAD

**Issue by neonguru** [awslabs/aws-support-tools#80]
I have a user pool that uses email to sign in. decode-verify-jwt works great for verifying the jwt token when I pass it to my server API, but it does not include the email. I need a way to verify the user's email in that API call. Is that information not stored in the jwt token?

The username returned in the claims is the user attribute sub value in guid format.

Basically I need a secure way to confirm the user's email server side.

**Comment by lpierillas** [comment]
From my testing, an attribute needs to be readable to be present in the jwt token. Using decode-verify-jwt.js I am able to see my user email in the ID token returned by Cognito if I configure it as readable in my app client settings.

This can be done in the Cognito console in General settings --> App clients --> Your app client --> Show details --> Set attribute read and write permissions --> Readable Attributes --> Save app client changes.
