### ISSUE TITLE
Cloudformer, adding elbv2 anytime soon?

### ISSUE THREAD

**Issue by tmblue** [awslabs/aws-support-tools#82]
Been over a year..  Are there any tools that would help create the elbv2.rb file?

**Comment by lpierillas** [comment]
Hi,

Thank you for your feedback. The CloudFormer tool in this repository is a fork created by AWS Premium Support engineers from the original CloudFormer beta tool presented here: 
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-using-cloudformer.html

The goal was to provide an easy solution to run CloudFormer into an existing VPC. However, we do not have any insight on when/if ELBV2 will be supported by the original tool. 

At the moment, we do not have any other tool in the repository that would allow you to generate templates and rb files from existing resources.

**Comment by wreuvenspam** [comment]
> Hi,
> 
> Thank you for your feedback. The CloudFormer tool in this repository is a fork created by AWS Premium Support engineers from the original CloudFormer beta tool presented here:
> https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-using-cloudformer.html
> 
> The goal was to provide an easy solution to run CloudFormer into an existing VPC. However, we do not have any insight on when/if ELBV2 will be supported by the original tool.
> 
> At the moment, we do not have any other tool in the repository that would allow you to generate templates and rb files from existing resources.

Is cloudformer open source? Who can I petition at Amazon to continue work on this critical project?

**Comment by lpierillas** [comment]
CloudFormer is not open source but from here it looks like you can download the code from the reference in the template if you want to tweak it for personal use:
https://forums.aws.amazon.com/thread.jspa?threadID=250155&tstart=0

For enquiries about CloudFormer I would recommend using our official AWS forum. This is the link to the CloudFormation discussion forum:
https://forums.aws.amazon.com/forum.jspa?forumID=92&start=0
