### ISSUE TITLE
decode-verify-jwt example, can we have this for Go language

### ISSUE THREAD

**Issue by dattatrayhkulkarni** [awslabs/aws-support-tools#90]
Is there any similar example for Go language?

**Comment by joshua-at-aws** [comment]
Hello,

There is no `golang` example right now.

By the way, if you would like to publish a reusable serverless application under an approved open source license such as Apache-2.0, you can do so using the AWS Serverless Application Repository

https://docs.aws.amazon.com/serverlessrepo/latest/devguide/serverlessrepo-quick-start.html

Those applications can be both used as a reference and easily deployed directly from https://serverlessrepo.aws.amazon.com/applications
