### ISSUE TITLE
Timeout when used on Lambda, fine locally though

### ISSUE THREAD

**Issue by JosephKav** [awslabs/aws-support-tools#95]
When I call my lambda function with postman I just get an "Internal server error" with a 3 second timeout on cloudwatch (Task timed out after 3.00 seconds). There's only 2 keys it needs to retrieve from that url and it loads pretty much instantly on my desktop. Are there any specific roles I need to run it as, or permissions I need to enable anywhere?

**Comment by lpierillas** [comment]
Hi,

Thank you for reaching out. I am not sure which tool you are referring to. Could you please give us more details about which Lambda sample in this repo is returning this error so we can help investigate?

If this is a general question about Lambda and not one of our samples, I would recommend reaching out on the AWS forum here instead:
https://forums.aws.amazon.com/forum.jspa?forumID=186

**Comment by JosephKav** [comment]
Oh, I thought it was going to be listed on the folder I put the issue from. This is when I use the cognito decoder for the JWT. It just can't seem to get and of the JWK's from cognito-idp. I'm using the python script on 2.7. I also ported it to python 3 by just adding urllib.request but neither worked when on lambda

**Comment by JosephKav** [comment]
Sorted it. All cause I had the function in a VPC

**Comment by JosephKav** [comment]
Sorted it. All cause I had the function in a VPC
