### ISSUE TITLE
Question on URL to get private key and if Lambda required 

### ISSUE THREAD

**Issue by NealWalters** [awslabs/aws-support-tools#96]
Part 1: 
Relating to: "decode-verify-jwt:. 
Does this code only run within Lambda for some security reason? 

Should I be able to go to the following URL and download or view the token? 
`   var keys_url = 'https://cognito-idp.' + region + '.amazonaws.com/' + userpool_id + '/.well-known/jwks.json';`

From an EC2 instance, I tried that url in a browser and I get "We can’t connect to the server at cognito-idp.amazonaws.com."  Is it publicly available?  I'm not supposed to create my own "Amazong Cognito Domain" (prefixed domain) and use that? 

Hour later - looks like I resolved this: I guess I was not including the region in the URL. 
Seems to work in browser now too. 

Part 2 - How to test in Lambda? No sample how to call it from Node-JS? 

I set up a test event within Lambda as follows: 

```
{
  "event": 
     {"token": "copied my whole token here that I got from a console.log when I first got the token"},
}
```

I've been away from Lambda for about a year, finally tried this and got the token passed in: 
```
{
     "token": "copied my whole token here that I got from a console.log when I first got the token"
}
```
It was dying in the token.split, so I added this: 

```
    console.log("====== start log");
    console.dir(event, { depth: null });
    var token = event.token;
    console.log ("token=" + token);
```

I also added a console.log as follows: 

```
    https.get(keys_url, function(response) {
          console.log("response.statusCode=" + response.statusCode +  "keys_url:" + keys_url); 
           if (response.statusCode == 200) {
```

Thanks,
Neal

**Comment by NealWalters** [comment]
Hour later - looks like I resolved this: I guess I was not including the region in the URL.
Seems to work in browser now too. But more doc/examples on how to call it would be nice, and don't insist that it be run in Lambda.  I'm writing my test app on an EC2 instance and will move to Lambda eventually.

**Comment by SudarAbisheck** [comment]
Thanks for your suggestions. Feel free to send a pull request for the same.
